<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Area;
use Illuminate\Support\Str;

class AreaSeeder extends Seeder
{
    public function run(): void
    {
        $areas = [
            [
                'title' => 'Los Angeles',
                'thumbnail' => 'areas/thumbnails/los-angeles.jpg',
                'banner' => 'areas/banners/los-angeles-banner.jpg',
                'banner_title' => 'Security Services in Los Angeles',
                'description' => '<p>Ready 24h Security provides comprehensive security solutions throughout Los Angeles. Our services include:</p><ul><li>Armed and unarmed security guards</li><li>Event security</li><li>Mobile patrol services</li><li>Access control systems</li><li>24/7 monitoring and response</li></ul><p>With our extensive experience in the LA area, we understand the unique security challenges of this vibrant city and provide tailored solutions to meet your needs.</p>',
                'meta_description' => 'Professional security services in Los Angeles. 24/7 armed and unarmed security guards, event security, and mobile patrol services.',
                'order' => 1,
                'active' => true,
            ],
            [
                'title' => 'San Francisco',
                'thumbnail' => 'areas/thumbnails/san-francisco.jpg',
                'banner' => 'areas/banners/san-francisco-banner.jpg',
                'banner_title' => 'Security Services in San Francisco',
                'description' => '<p>Protect your business and property in San Francisco with our professional security services. We offer:</p><ul><li>Commercial property security</li><li>Residential security</li><li>Event security</li><li>VIP protection</li><li>Emergency response services</li></ul><p>Our team of trained professionals is ready to serve the unique security needs of San Francisco businesses and residents.</p>',
                'meta_description' => 'Reliable security services in San Francisco. Commercial and residential security, event security, and VIP protection services.',
                'order' => 2,
                'active' => true,
            ],
            [
                'title' => 'San Diego',
                'thumbnail' => 'areas/thumbnails/san-diego.jpg',
                'banner' => 'areas/banners/san-diego-banner.jpg',
                'banner_title' => 'Security Services in San Diego',
                'description' => '<p>Comprehensive security solutions for San Diego businesses and residents. Our services include:</p><ul><li>Beach and waterfront security</li><li>Hotel and resort security</li><li>Retail security</li><li>Construction site security</li><li>Special event security</li></ul><p>Trust Ready 24h Security to keep your property and assets safe in San Diego.</p>',
                'meta_description' => 'Professional security services in San Diego. Beach security, hotel security, retail security, and special event security.',
                'order' => 3,
                'active' => true,
            ],
            [
                'title' => 'San Jose',
                'thumbnail' => 'areas/thumbnails/san-jose.jpg',
                'banner' => 'areas/banners/san-jose-banner.jpg',
                'banner_title' => 'Security Services in San Jose',
                'description' => '<p>Silicon Valley\'s security needs are unique, and we\'re here to meet them. Our services include:</p><ul><li>Tech company security</li><li>Data center protection</li><li>Corporate campus security</li><li>Executive protection</li><li>24/7 monitoring</li></ul><p>We understand the high-tech environment and provide security solutions that match the innovation of Silicon Valley.</p>',
                'meta_description' => 'Specialized security services for Silicon Valley. Tech company security, data center protection, and corporate campus security.',
                'order' => 4,
                'active' => true,
            ],
            [
                'title' => 'Sacramento',
                'thumbnail' => 'areas/thumbnails/sacramento.jpg',
                'banner' => 'areas/banners/sacramento-banner.jpg',
                'banner_title' => 'Security Services in Sacramento',
                'description' => '<p>State capital security requires special attention. We provide:</p><ul><li>Government building security</li><li>Event security</li><li>Downtown patrol services</li><li>Residential security</li><li>Emergency response</li></ul><p>Our team is trained to handle the unique security needs of California\'s capital city.</p>',
                'meta_description' => 'Professional security services in Sacramento. Government building security, event security, and downtown patrol services.',
                'order' => 5,
                'active' => true,
            ],
            [
                'title' => 'Fresno',
                'thumbnail' => 'areas/thumbnails/fresno.jpg',
                'banner' => 'areas/banners/fresno-banner.jpg',
                'banner_title' => 'Security Services in Fresno',
                'description' => '<p>Central Valley security solutions tailored to your needs:</p><ul><li>Agricultural facility security</li><li>Industrial security</li><li>Retail security</li><li>Event security</li><li>Mobile patrol services</li></ul><p>We understand the unique challenges of Central Valley businesses and provide effective security solutions.</p>',
                'meta_description' => 'Comprehensive security services in Fresno. Agricultural facility security, industrial security, and retail security.',
                'order' => 6,
                'active' => true,
            ],
            [
                'title' => 'Long Beach',
                'thumbnail' => 'areas/thumbnails/long-beach.jpg',
                'banner' => 'areas/banners/long-beach-banner.jpg',
                'banner_title' => 'Security Services in Long Beach',
                'description' => '<p>Port city security requires specialized attention. We offer:</p><ul><li>Port facility security</li><li>Maritime security</li><li>Beach security</li><li>Event security</li><li>Commercial property protection</li></ul><p>Our team is experienced in handling the unique security needs of Long Beach\'s diverse environment.</p>',
                'meta_description' => 'Specialized security services in Long Beach. Port facility security, maritime security, and beach security.',
                'order' => 7,
                'active' => true,
            ],
            [
                'title' => 'Oakland',
                'thumbnail' => 'areas/thumbnails/oakland.jpg',
                'banner' => 'areas/banners/oakland-banner.jpg',
                'banner_title' => 'Security Services in Oakland',
                'description' => '<p>Comprehensive security solutions for Oakland businesses:</p><ul><li>Port security</li><li>Industrial security</li><li>Commercial property protection</li><li>Event security</li><li>24/7 monitoring</li></ul><p>We provide reliable security services throughout the Oakland area.</p>',
                'meta_description' => 'Professional security services in Oakland. Port security, industrial security, and commercial property protection.',
                'order' => 8,
                'active' => true,
            ],
            [
                'title' => 'Anaheim',
                'thumbnail' => 'areas/thumbnails/anaheim.jpg',
                'banner' => 'areas/banners/anaheim-banner.jpg',
                'banner_title' => 'Security Services in Anaheim',
                'description' => '<p>Tourist destination security requires special attention. We provide:</p><ul><li>Theme park security</li><li>Hotel security</li><li>Event security</li><li>Retail security</li><li>Tourist area patrols</li></ul><p>Our team is experienced in handling the unique security needs of Anaheim\'s tourist attractions.</p>',
                'meta_description' => 'Specialized security services in Anaheim. Theme park security, hotel security, and event security.',
                'order' => 9,
                'active' => true,
            ],
            [
                'title' => 'Santa Ana',
                'thumbnail' => 'areas/thumbnails/santa-ana.jpg',
                'banner' => 'areas/banners/santa-ana-banner.jpg',
                'banner_title' => 'Security Services in Santa Ana',
                'description' => '<p>Orange County security solutions for your needs:</p><ul><li>Commercial security</li><li>Residential security</li><li>Event security</li><li>Retail security</li><li>Mobile patrol services</li></ul><p>We provide comprehensive security services throughout Santa Ana.</p>',
                'meta_description' => 'Professional security services in Santa Ana. Commercial security, residential security, and event security.',
                'order' => 10,
                'active' => true,
            ],
            [
                'title' => 'Riverside',
                'thumbnail' => 'areas/thumbnails/riverside.jpg',
                'banner' => 'areas/banners/riverside-banner.jpg',
                'banner_title' => 'Security Services in Riverside',
                'description' => '<p>Inland Empire security solutions:</p><ul><li>Industrial security</li><li>Commercial property protection</li><li>Residential security</li><li>Event security</li><li>Mobile patrol services</li></ul><p>We understand the unique security needs of Riverside businesses and residents.</p>',
                'meta_description' => 'Comprehensive security services in Riverside. Industrial security, commercial property protection, and residential security.',
                'order' => 11,
                'active' => true,
            ],
            [
                'title' => 'Bakersfield',
                'thumbnail' => 'areas/thumbnails/bakersfield.jpg',
                'banner' => 'areas/banners/bakersfield-banner.jpg',
                'banner_title' => 'Security Services in Bakersfield',
                'description' => '<p>Central Valley security solutions:</p><ul><li>Agricultural facility security</li><li>Industrial security</li><li>Oil field security</li><li>Commercial property protection</li><li>Event security</li></ul><p>We provide specialized security services for Bakersfield\'s unique industries.</p>',
                'meta_description' => 'Professional security services in Bakersfield. Agricultural facility security, industrial security, and oil field security.',
                'order' => 12,
                'active' => true,
            ],
            [
                'title' => 'Stockton',
                'thumbnail' => 'areas/thumbnails/stockton.jpg',
                'banner' => 'areas/banners/stockton-banner.jpg',
                'banner_title' => 'Security Services in Stockton',
                'description' => '<p>Port city security solutions:</p><ul><li>Port facility security</li><li>Industrial security</li><li>Commercial property protection</li><li>Event security</li><li>Mobile patrol services</li></ul><p>We provide comprehensive security services throughout Stockton.</p>',
                'meta_description' => 'Professional security services in Stockton. Port facility security, industrial security, and commercial property protection.',
                'order' => 13,
                'active' => true,
            ],
            [
                'title' => 'Irvine',
                'thumbnail' => 'areas/thumbnails/irvine.jpg',
                'banner' => 'areas/banners/irvine-banner.jpg',
                'banner_title' => 'Security Services in Irvine',
                'description' => '<p>Business district security solutions:</p><ul><li>Corporate security</li><li>Commercial property protection</li><li>Residential security</li><li>Event security</li><li>Mobile patrol services</li></ul><p>We provide specialized security services for Irvine\'s business community.</p>',
                'meta_description' => 'Professional security services in Irvine. Corporate security, commercial property protection, and residential security.',
                'order' => 14,
                'active' => true,
            ],
            [
                'title' => 'Chula Vista',
                'thumbnail' => 'areas/thumbnails/chula-vista.jpg',
                'banner' => 'areas/banners/chula-vista-banner.jpg',
                'banner_title' => 'Security Services in Chula Vista',
                'description' => '<p>Border city security solutions:</p><ul><li>Commercial security</li><li>Residential security</li><li>Event security</li><li>Retail security</li><li>Mobile patrol services</li></ul><p>We provide comprehensive security services throughout Chula Vista.</p>',
                'meta_description' => 'Professional security services in Chula Vista. Commercial security, residential security, and event security.',
                'order' => 15,
                'active' => true,
            ],
            [
                'title' => 'Fremont',
                'thumbnail' => 'areas/thumbnails/fremont.jpg',
                'banner' => 'areas/banners/fremont-banner.jpg',
                'banner_title' => 'Security Services in Fremont',
                'description' => '<p>Silicon Valley security solutions:</p><ul><li>Tech company security</li><li>Industrial security</li><li>Commercial property protection</li><li>Event security</li><li>Mobile patrol services</li></ul><p>We provide specialized security services for Fremont\'s diverse business community.</p>',
                'meta_description' => 'Professional security services in Fremont. Tech company security, industrial security, and commercial property protection.',
                'order' => 16,
                'active' => true,
            ],
            [
                'title' => 'Modesto',
                'thumbnail' => 'areas/thumbnails/modesto.jpg',
                'banner' => 'areas/banners/modesto-banner.jpg',
                'banner_title' => 'Security Services in Modesto',
                'description' => '<p>Central Valley security solutions:</p><ul><li>Agricultural facility security</li><li>Industrial security</li><li>Commercial property protection</li><li>Event security</li><li>Mobile patrol services</li></ul><p>We provide comprehensive security services throughout Modesto.</p>',
                'meta_description' => 'Professional security services in Modesto. Agricultural facility security, industrial security, and commercial property protection.',
                'order' => 17,
                'active' => true,
            ],
            [
                'title' => 'Oxnard',
                'thumbnail' => 'areas/thumbnails/oxnard.jpg',
                'banner' => 'areas/banners/oxnard-banner.jpg',
                'banner_title' => 'Security Services in Oxnard',
                'description' => '<p>Coastal city security solutions:</p><ul><li>Port facility security</li><li>Agricultural security</li><li>Commercial property protection</li><li>Event security</li><li>Mobile patrol services</li></ul><p>We provide specialized security services for Oxnard\'s unique environment.</p>',
                'meta_description' => 'Professional security services in Oxnard. Port facility security, agricultural security, and commercial property protection.',
                'order' => 18,
                'active' => true,
            ],
            [
                'title' => 'Fontana',
                'thumbnail' => 'areas/thumbnails/fontana.jpg',
                'banner' => 'areas/banners/fontana-banner.jpg',
                'banner_title' => 'Security Services in Fontana',
                'description' => '<p>Industrial city security solutions:</p><ul><li>Industrial security</li><li>Commercial property protection</li><li>Residential security</li><li>Event security</li><li>Mobile patrol services</li></ul><p>We provide comprehensive security services throughout Fontana.</p>',
                'meta_description' => 'Professional security services in Fontana. Industrial security, commercial property protection, and residential security.',
                'order' => 19,
                'active' => true,
            ],
            [
                'title' => 'Moreno Valley',
                'thumbnail' => 'areas/thumbnails/moreno-valley.jpg',
                'banner' => 'areas/banners/moreno-valley-banner.jpg',
                'banner_title' => 'Security Services in Moreno Valley',
                'description' => '<p>Inland Empire security solutions:</p><ul><li>Industrial security</li><li>Commercial property protection</li><li>Residential security</li><li>Event security</li><li>Mobile patrol services</li></ul><p>We provide specialized security services for Moreno Valley businesses and residents.</p>',
                'meta_description' => 'Professional security services in Moreno Valley. Industrial security, commercial property protection, and residential security.',
                'order' => 20,
                'active' => true,
            ],
            [
                'title' => 'Glendale',
                'thumbnail' => 'areas/thumbnails/glendale.jpg',
                'banner' => 'areas/banners/glendale-banner.jpg',
                'banner_title' => 'Security Services in Glendale',
                'description' => '<p>Los Angeles area security solutions:</p><ul><li>Commercial security</li><li>Residential security</li><li>Event security</li><li>Retail security</li><li>Mobile patrol services</li></ul><p>We provide comprehensive security services throughout Glendale.</p>',
                'meta_description' => 'Professional security services in Glendale. Commercial security, residential security, and event security.',
                'order' => 21,
                'active' => true,
            ],
            [
                'title' => 'Huntington Beach',
                'thumbnail' => 'areas/thumbnails/huntington-beach.jpg',
                'banner' => 'areas/banners/huntington-beach-banner.jpg',
                'banner_title' => 'Security Services in Huntington Beach',
                'description' => '<p>Beach city security solutions:</p><ul><li>Beach security</li><li>Commercial property protection</li><li>Residential security</li><li>Event security</li><li>Mobile patrol services</li></ul><p>We provide specialized security services for Huntington Beach\'s unique environment.</p>',
                'meta_description' => 'Professional security services in Huntington Beach. Beach security, commercial property protection, and residential security.',
                'order' => 22,
                'active' => true,
            ],
            [
                'title' => 'Santa Clarita',
                'thumbnail' => 'areas/thumbnails/santa-clarita.jpg',
                'banner' => 'areas/banners/santa-clarita-banner.jpg',
                'banner_title' => 'Security Services in Santa Clarita',
                'description' => '<p>Valley security solutions:</p><ul><li>Commercial security</li><li>Residential security</li><li>Event security</li><li>Retail security</li><li>Mobile patrol services</li></ul><p>We provide comprehensive security services throughout Santa Clarita.</p>',
                'meta_description' => 'Professional security services in Santa Clarita. Commercial security, residential security, and event security.',
                'order' => 23,
                'active' => true,
            ],
            [
                'title' => 'Garden Grove',
                'thumbnail' => 'areas/thumbnails/garden-grove.jpg',
                'banner' => 'areas/banners/garden-grove-banner.jpg',
                'banner_title' => 'Security Services in Garden Grove',
                'description' => '<p>Orange County security solutions:</p><ul><li>Commercial security</li><li>Residential security</li><li>Event security</li><li>Retail security</li><li>Mobile patrol services</li></ul><p>We provide specialized security services for Garden Grove businesses and residents.</p>',
                'meta_description' => 'Professional security services in Garden Grove. Commercial security, residential security, and event security.',
                'order' => 24,
                'active' => true,
            ],
            [
                'title' => 'Oceanside',
                'thumbnail' => 'areas/thumbnails/oceanside.jpg',
                'banner' => 'areas/banners/oceanside-banner.jpg',
                'banner_title' => 'Security Services in Oceanside',
                'description' => '<p>Coastal city security solutions:</p><ul><li>Beach security</li><li>Commercial property protection</li><li>Residential security</li><li>Event security</li><li>Mobile patrol services</li></ul><p>We provide comprehensive security services throughout Oceanside.</p>',
                'meta_description' => 'Professional security services in Oceanside. Beach security, commercial property protection, and residential security.',
                'order' => 25,
                'active' => true,
            ],
            [
                'title' => 'Rancho Cucamonga',
                'thumbnail' => 'areas/thumbnails/rancho-cucamonga.jpg',
                'banner' => 'areas/banners/rancho-cucamonga-banner.jpg',
                'banner_title' => 'Security Services in Rancho Cucamonga',
                'description' => '<p>Inland Empire security solutions:</p><ul><li>Commercial security</li><li>Residential security</li><li>Event security</li><li>Retail security</li><li>Mobile patrol services</li></ul><p>We provide specialized security services for Rancho Cucamonga businesses and residents.</p>',
                'meta_description' => 'Professional security services in Rancho Cucamonga. Commercial security, residential security, and event security.',
                'order' => 26,
                'active' => true,
            ],
            [
                'title' => 'Santa Rosa',
                'thumbnail' => 'areas/thumbnails/santa-rosa.jpg',
                'banner' => 'areas/banners/santa-rosa-banner.jpg',
                'banner_title' => 'Security Services in Santa Rosa',
                'description' => '<p>Wine country security solutions:</p><ul><li>Vineyard security</li><li>Commercial property protection</li><li>Residential security</li><li>Event security</li><li>Mobile patrol services</li></ul><p>We provide comprehensive security services throughout Santa Rosa.</p>',
                'meta_description' => 'Professional security services in Santa Rosa. Vineyard security, commercial property protection, and residential security.',
                'order' => 27,
                'active' => true,
            ],
            [
                'title' => 'Ontario',
                'thumbnail' => 'areas/thumbnails/ontario.jpg',
                'banner' => 'areas/banners/ontario-banner.jpg',
                'banner_title' => 'Security Services in Ontario',
                'description' => '<p>Inland Empire security solutions:</p><ul><li>Airport security</li><li>Industrial security</li><li>Commercial property protection</li><li>Event security</li><li>Mobile patrol services</li></ul><p>We provide specialized security services for Ontario\'s unique business environment.</p>',
                'meta_description' => 'Professional security services in Ontario. Airport security, industrial security, and commercial property protection.',
                'order' => 28,
                'active' => true,
            ],
            [
                'title' => 'Elk Grove',
                'thumbnail' => 'areas/thumbnails/elk-grove.jpg',
                'banner' => 'areas/banners/elk-grove-banner.jpg',
                'banner_title' => 'Security Services in Elk Grove',
                'description' => '<p>Sacramento area security solutions:</p><ul><li>Commercial security</li><li>Residential security</li><li>Event security</li><li>Retail security</li><li>Mobile patrol services</li></ul><p>We provide comprehensive security services throughout Elk Grove.</p>',
                'meta_description' => 'Professional security services in Elk Grove. Commercial security, residential security, and event security.',
                'order' => 29,
                'active' => true,
            ],
            [
                'title' => 'Corona',
                'thumbnail' => 'areas/thumbnails/corona.jpg',
                'banner' => 'areas/banners/corona-banner.jpg',
                'banner_title' => 'Security Services in Corona',
                'description' => '<p>Inland Empire security solutions:</p><ul><li>Commercial security</li><li>Residential security</li><li>Event security</li><li>Retail security</li><li>Mobile patrol services</li></ul><p>We provide specialized security services for Corona businesses and residents.</p>',
                'meta_description' => 'Professional security services in Corona. Commercial security, residential security, and event security.',
                'order' => 30,
                'active' => true,
            ],
        ];

        foreach ($areas as $area) {
            Area::create($area);
        }
    }
} 